version: 0.2

env:
  parameter-store:
    QTEST_SUBDOMAIN: "/qtest-library-pipeline/testing/subdomain"
    QTEST_USER: "/qtest-library-pipeline/testing/username"
    QTEST_PASS: "/qtest-library-pipeline/testing/password"

phases:
  pre_build:
    commands:
      - chmod +x ./gradlew
  build:
    commands:
      - ./gradlew build
      - ./gradlew test
  post_build:
    commands:
      - '[[ "${CODEBUILD_BUILD_SUCCEEDING}" -ne 1 ]] && exit 1 || echo "Build suceeded!"'
